language: java

jdk:
    - openjdk8

jobs:
    include:
        - stage: build
          name: jar
          script: mvn --batch-mode --define java.net.useSystemProxies=true clean compile assembly:single
